import { useState, useCallback, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Key, ShieldCheck, Activity, ArrowRightLeft, ShieldAlert } from 'lucide-react';
import { useDemoSession } from '../../hooks/useDemoSession';
import { Button } from '../ui/Button';
import { Card } from '../ui/Card';
import { Heading } from '../ui/Heading';
import { Stack } from '../ui/Stack';
import { Pill } from '../ui/Pill';
import { Glass } from '../ui/Glass';
import { cn, formatDuration } from '../../lib/utils';
import type { RequestMetadata } from '../../lib/api/demo-client';

interface TokenEvent {
  id: string;
  timestamp: Date;
  status: 'valid' | 'invalid' | 'rotating';
  message: string;
}

export function VaultRotationDemo() {
  const [logs, setLogs] = useState<TokenEvent[]>([]);
  const [dbState, setDbState] = useState<'connected' | 'auth_failed'>('connected');
  const [isRotating, setIsRotating] = useState(false);
  const [receipts, setReceipts] = useState<RequestMetadata[]>([]);

  const { executeCommand, events, chaos } = useDemoSession('vault');

  const verifyConnection = useCallback(async () => {
    try {
      const res = await executeCommand('/vault/status', {}, {method: 'GET'});
      
      setLogs(prev => [{
        id: crypto.randomUUID(),
        timestamp: new Date(),
        status: res?.success ? 'valid' : 'invalid',
        message: res?.success ? 'DB Auth Success' : 'DB Auth Failed (401)'
      }, ...prev].slice(0, 8));

      setDbState(res?.success ? 'connected' : 'auth_failed');
      if (res?.metadata) setReceipts(prev => [res.metadata, ...prev].slice(0, 5));
    } catch (e) {
      setDbState('auth_failed');
      setLogs(prev => [{
        id: crypto.randomUUID(),
        timestamp: new Date(),
        status: 'invalid',
        message: 'DB Auth Failed (401)'
      }, ...prev].slice(0, 8));
    }
  }, [executeCommand]);

  const rotateCredentials = useCallback(async () => {
    setIsRotating(true);
    setLogs(prev => [{
      id: crypto.randomUUID(),
      timestamp: new Date(),
      status: 'rotating',
      message: 'Revoking dynamic lease...'
    }, ...prev].slice(0, 8));

    try {
      await executeCommand('/vault/rotate');
      setTimeout(verifyConnection, 1000);
    } finally {
      setIsRotating(false);
    }
  }, [executeCommand, verifyConnection]);

  return (
    <div className="grid lg:grid-cols-2 gap-8">
      <Stack gap={6}>
        <div className="flex items-center justify-between">
          <Heading variant="caption" className="flex items-center gap-2.5">
            <Key className="w-4 h-4 text-accent" />
            Dynamic Credentials
          </Heading>
        </div>

        <Card variant="panel-dark" padding="lg">
          <Stack gap={8} className="font-mono">
            <Stack gap={4}>
              <div className="flex justify-between items-center text-[10px] font-black uppercase tracking-widest text-muted/90">
                <span>Vault Lease State</span>
                <Pill variant={dbState === 'connected' ? 'success' : 'error'}>
                  {dbState === 'connected' ? 'ACTIVE' : 'REVOKED'}
                </Pill>
              </div>

              <div className={cn(
                "p-6 rounded-xl border relative overflow-hidden transition-colors",
                dbState === 'connected' ? "bg-success/5 border-success/30" : "bg-error/10 border-error/50"
              )}>
                {dbState === 'auth_failed' && (
                  <div className="absolute inset-0 bg-error/5 animate-pulse pointer-events-none" />
                )}
                
                <div className="flex flex-col gap-4 relative z-10">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <ShieldCheck className={cn("w-5 h-5", dbState === 'connected' ? 'text-success' : 'text-error')} />
                      <span className="text-xs font-black uppercase tracking-widest">
                        PG_ROLE: identity_owner
                      </span>
                    </div>
                  </div>
                  
                  <div className="text-[10px] text-muted/80 leading-relaxed">
                    Credentials generated by Vault are tied to a TTL lease. 
                    The application transparently re-authenticates when the lease expires or is manually revoked.
                  </div>
                </div>
              </div>
            </Stack>

            <div className="grid grid-cols-2 gap-3">
              <Button
                variant="primary"
                onClick={verifyConnection}
                disabled={isRotating}
                className="w-full h-auto py-4 font-black text-xs uppercase tracking-widest rounded-2xl flex items-center justify-center gap-2"
              >
                Test Query
              </Button>
              <Button
                variant="secondary"
                onClick={rotateCredentials}
                disabled={isRotating}
                className="w-full h-auto py-4 font-black text-xs uppercase tracking-widest rounded-2xl flex items-center justify-center gap-2 border-warning/30 text-warning hover:bg-warning/10"
              >
                Revoke Lease
              </Button>
            </div>
          </Stack>
        </Card>
      </Stack>

      <Stack gap={6}>
        <Heading variant="caption" className="flex items-center gap-2.5">
          <Activity className="w-4 h-4 text-muted" />
          Auth Log
        </Heading>

        <Card variant="panel-dark" padding="none" className="h-[440px] flex flex-col overflow-hidden">
          <div className="flex-1 overflow-y-auto font-mono text-[11px]">
            <table className="w-full text-left border-collapse">
              <thead className="sticky top-0 bg-[#0d0d12] border-b border-white/10 z-10 text-muted/90 uppercase text-[10px] font-black tracking-widest">
                <tr>
                  <th className="px-6 py-4">Timestamp</th>
                  <th className="px-6 py-4">Event</th>
                </tr>
              </thead>
              <tbody>
                <AnimatePresence initial={false}>
                  {logs.length === 0 ? (
                    <tr>
                      <td colSpan={2} className="py-24 text-center text-muted/80 italic uppercase tracking-[0.4em] font-black">
                        Test connection or rotate lease
                      </td>
                    </tr>
                  ) : (
                    logs.map((log) => (
                      <motion.tr
                        key={log.id}
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        className="group border-b border-white/[0.02] hover:bg-white/[0.02] transition-colors"
                      >
                        <td className="px-6 py-4 text-muted/80 text-[10px]">
                          {log.timestamp.toLocaleTimeString()}
                        </td>
                        <td className="px-6 py-4">
                          {log.status === 'valid' ? (
                            <span className="text-success uppercase font-black tracking-wider">{log.message}</span>
                          ) : log.status === 'rotating' ? (
                            <span className="text-warning uppercase font-black tracking-wider flex items-center gap-2">
                              <ArrowRightLeft className="w-3 h-3 animate-spin" />
                              {log.message}
                            </span>
                          ) : (
                            <span className="text-error uppercase font-black tracking-wider flex items-center gap-2">
                              <ShieldAlert className="w-3 h-3" />
                              {log.message}
                            </span>
                          )}
                        </td>
                      </motion.tr>
                    ))
                  )}
                </AnimatePresence>
              </tbody>
            </table>
          </div>
        </Card>
      </Stack>
    </div>
  );
}
