# =============================================================================
# Portfolio Showcase Infrastructure
# =============================================================================
# Deploys the complete infrastructure for the portfolio showcase:
# - Neon PostgreSQL (free tier)
# - Upstash Redis (free tier)
# - CloudAMQP RabbitMQ (free tier)
# - Fly.io API + Vault (free tier)
# - Cloudflare DNS + Pages (free tier)
# =============================================================================

# -----------------------------------------------------------------------------
# Provider Configuration
# -----------------------------------------------------------------------------
provider "neon" {
  api_key = var.neon_api_key
}

provider "fly" {
  fly_api_token = var.fly_api_token
}

provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

# -----------------------------------------------------------------------------
# Random Password Generation
# -----------------------------------------------------------------------------
resource "random_password" "vault_token" {
  length  = 32
  special = false
}

resource "random_password" "db_password" {
  length  = 24
  special = false
}

# -----------------------------------------------------------------------------
# Neon PostgreSQL
# -----------------------------------------------------------------------------
module "neon" {
  source = "./modules/neon"

  project_name = var.neon_project_name
  db_name      = "portfolio"
  db_user      = "portfolio_app"
  db_password  = random_password.db_password.result
}

# -----------------------------------------------------------------------------
# Upstash Redis
# -----------------------------------------------------------------------------
module "upstash" {
  source = "./modules/upstash"

  api_key       = var.upstash_api_key
  email         = var.upstash_email
  database_name = "portfolio-cache"
  region        = "eu-west-1"
}

# -----------------------------------------------------------------------------
# CloudAMQP RabbitMQ
# -----------------------------------------------------------------------------
module "cloudamqp" {
  source = "./modules/cloudamqp"

  api_key       = var.cloudamqp_api_key
  instance_name = "portfolio-mq"
  region        = "amazon-web-services::eu-west-1"
}

# -----------------------------------------------------------------------------
# Fly.io Applications
# -----------------------------------------------------------------------------

# Vault (dev mode)
module "vault" {
  source = "./modules/flyio"

  app_name    = "portfolio-vault"
  org         = var.fly_org
  region      = var.fly_region
  image       = "hashicorp/vault:1.15"
  internal    = true

  env = {
    VAULT_DEV_ROOT_TOKEN_ID = random_password.vault_token.result
    VAULT_DEV_LISTEN_ADDRESS = "0.0.0.0:8200"
  }

  services = [{
    internal_port = 8200
    protocol      = "tcp"
    ports = [{
      port     = 8200
      handlers = ["http"]
    }]
  }]
}

# API Application
module "api" {
  source = "./modules/flyio"

  app_name = "portfolio-api"
  org      = var.fly_org
  region   = var.fly_region
  image    = "registry.fly.io/portfolio-api:latest"

  env = {
    ASPNETCORE_ENVIRONMENT = "Demo"
    ASPNETCORE_URLS        = "http://+:8080"

    # These will be populated after first deploy
    ConnectionStrings__Default = module.neon.connection_string
    ConnectionStrings__Redis   = module.upstash.connection_string
    RabbitMQ__Host             = module.cloudamqp.host
    RabbitMQ__Username         = module.cloudamqp.username
    RabbitMQ__Password         = module.cloudamqp.password

    Vault__Address      = "http://portfolio-vault.internal:8200"
    Vault__DevMode      = "true"
    Vault__DevRootToken = random_password.vault_token.result
  }

  services = [{
    internal_port = 8080
    protocol      = "tcp"
    ports = [
      { port = 80, handlers = ["http"] },
      { port = 443, handlers = ["http", "tls"] }
    ]
  }]

  depends_on = [module.vault, module.neon, module.upstash, module.cloudamqp]
}

# -----------------------------------------------------------------------------
# Cloudflare DNS & Pages
# -----------------------------------------------------------------------------
module "cloudflare" {
  source = "./modules/cloudflare"

  zone_id     = var.cloudflare_zone_id
  domain_name = var.domain_name

  # DNS records for Fly.io
  api_hostname = module.api.hostname

  depends_on = [module.api]
}

# -----------------------------------------------------------------------------
# Local Files for Application Configuration
# -----------------------------------------------------------------------------
resource "local_file" "env_file" {
  filename = "${path.module}/../.env.generated"
  content  = <<-EOT
    # Generated by Terraform - ${timestamp()}
    # Copy these to your application's environment

    # Database (Neon PostgreSQL)
    DATABASE_URL=${module.neon.connection_string}

    # Redis (Upstash)
    REDIS_URL=${module.upstash.connection_string}

    # RabbitMQ (CloudAMQP)
    RABBITMQ_URL=${module.cloudamqp.amqp_url}

    # Vault
    VAULT_ADDR=http://portfolio-vault.internal:8200
    VAULT_TOKEN=${random_password.vault_token.result}

    # Fly.io
    FLY_API_HOSTNAME=${module.api.hostname}

    # Domain
    DOMAIN=${var.domain_name}
  EOT

  file_permission = "0600"
}
